### ISSUE TITLE
screenshot on element (yet) not working

### ISSUE THREAD

**Issue by m9dfukc** [jackrusher/sparkledriver#12]
According to the [documentation](https://jackrusher.github.io/sparkledriver/sparkledriver.element.html#var-screenshot) the `screenshot` function takes either `browser` or `element` ... unfortunately I am getting a `Screenshot not supported on jBrowserDriver WebElements` exception.

This jBrowserDriver [issue report](https://github.com/MachinePublishers/jBrowserDriver/issues/256) indicates that this feature is (yet) not implemented. You might adapt your documentation to avoid confusion.

**Comment by jackrusher** [comment]
Thanks for the report! I've fixed the doc, and will revisit when the upstream problem is resolved.
