### ISSUE TITLE
src file missing

### ISSUE THREAD

**Issue by m9dfukc** [jackrusher/sparkledriver#13]
Hi,

is it me or am I doing something wrong ... looks like the `src/sparkledriver/core.clj` is missing since release 0.2.0?!

**Comment by m9dfukc** [comment]
Just checked the CHANGELOG.md "Reorganized the code into multiple namespaces, by function"  ok, got that ... but the sourcecode is missing ;)

**Comment by jackrusher** [comment]
The samples were also updated:
```
(require '[sparkledriver.browser :refer [with-browser make-browser fetch!]])
(require '[sparkledriver.element :refer [find-by-xpath* text]])
```
... is it not working for you? :)

**Comment by m9dfukc** [comment]
I've pulled in the .jar from maven which indeed works fine. Actually I am talking about this repo, the `src` folder seems be be gone.

**Comment by jackrusher** [comment]
Good grief, that's bizarre. I've fixed it now.
