### ISSUE TITLE
close-browser! hangs with multiple windows

### ISSUE THREAD

**Issue by ifell** [jackrusher/sparkledriver#17]
If you try to close the browser when the current browser is not 0, then close-browser! stalls.

For example, this code stalls
(def browser (make-browser))
(fetch! browser "https://www.google.com")
(execute-script browser "window.open('https://www.amazon.com');")
(switch-to-window browser "1")
;; do stuff in new browser window
(close-browser! browser)

but this code works and closes the browser
(def browser (make-browser))
(fetch! browser "https://www.google.com")
(execute-script browser "window.open('https://www.amazon.com');")
(switch-to-window browser "1")
;; do stuff in new browser window
(switch-to-window browser "0") ;; this is required otherwise close-browser! hangs
(close-browser! browser)

perhaps close-browser! should always switch to 0 before closing?

**Comment by jackrusher** [comment]
The good news is that I can reproduce the bug. The bad news is that switching to window "0" isn't fixing the problem in my tests. :(

**Comment by jackrusher** [comment]
Thanks for the report, @ifell. I have a fix for this in `0.2.1`.
