### ISSUE TITLE
Consider tagging releases

### ISSUE THREAD

**Issue by martinklepsch** [jackrusher/sparkledriver#20]
🙂

**Comment by jackrusher** [comment]
Done :)

**Comment by martinklepsch** [comment]
Now with that done you could also link to cljdoc for your docs (they will update automatically whenever you publish a new release): 

https://cljdoc.xyz/d/sparkledriver/sparkledriver/0.2.3

[![sparkledriver cljdoc badge](https://cljdoc.xyz/badge/sparkledriver)](https://cljdoc.xyz/d/sparkledriver/sparkledriver/CURRENT)
