### ISSUE TITLE
Fails when used with lucidity library for clojure

### ISSUE THREAD

**Issue by abhi18av** [jackrusher/sparkledriver#21]
Hi @jackrusher 

I'm reporting an issue regarding the failure of `jBrowserDriver` engine to start when I included `https://clojars.org/zcaudate/lucid` as a dependency.

Here's my configuration 

```clojure 
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [sparkledriver "0.2.2"]
;; This inclusion causes many errors in the code
                 [zcaudate/lucid "1.4.4"]
                ; [zcaudate/lucid "1.4.4" :exclusions [org.slf4j/slf4j-log4j] ]


]


```

**Comment by jackrusher** [comment]
Perhaps you should address this issue with the maintainer of `lucid`.
