### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by kwladyka** [jackrusher/sparkledriver#4]
Hi, i found your work and probably i have stupid question. Why your solution with WebKit is so slow?

`(fetch! browser "https://www.otodom.pl/oferta/zielone-tarasy-ID2QLph.html")` takes 15 sec. while in safari it takes 1 sec.

PS `http://clojure.org` load fast.
PS2 I am looking library for crawler.

**Comment by jackrusher** [comment]
I'm seeing ~10 seconds load times for that page from here. My assumption is that it takes that long for all the JS on the page to quiesce. (Safari starts rendering right away, whereas this library waits for the all pending JS to run so that any modifications made to the page by JS are available.)

**Comment by kwladyka** [comment]
Hi, thank you for answer. I checked it with chrome and developer tool in incognito. It takes 2,06 s. Something more has to be here, but no idea what.
