### ISSUE TITLE
API suggestions

### ISSUE THREAD

**Issue by plexus** [jackrusher/sparkledriver#8]
Hi Jack,

I've been putting SparkleDriver to use a bit more, and these were some of the things I ran into that could potentially be useful inside the library. If you tell me which of these you like then I'm happy to make a PR.

- call `(str)` on `fetch!` url

java.net.URI/java.net.URL/lambdaisland.uri.URI all return the url as a string when coerced to string, so this would make it possible to use these directly

- page-text

A simple helper

``` clojure
(defn page-text [] 
  (text (find-by-tag "html")))
```

- title

``` clojure
(defn title [] ;; or page-title?
  (sd/inner-html (sd/find-by-css browser "head title")))
```
- current-path

like `current-url` but only returns the path section, e.g. `"/profile"`

- wrap find-by-css / find-by-xpath to throw a more descriptive error message

If you look at the [jBrowserDriver implementation](https://github.com/MachinePublishers/jBrowserDriver/blob/master/src/com/machinepublishers/jbrowserdriver/Element.java#L67-L72) the exception just gets a generic message string, "Element not found", so you don't know which element is not found.

Instead the finders could catch the `NoSuchElementException`, and raise a slightly more helpful exception

**Comment by jackrusher** [comment]
Hey Arne,

1. I'm fine with coercing `fetch!`'s argument to a string,
2. `page-text` and `title` seem quite reasonable.
3. My initial inclination is to leave `current-path`-type functionality to another library, like the fine  `lambdaisland.uri`.
4. I've been on the fence between wrapping it and just changing the API so that not finding an element returns `nil`. There are tradeoffs and I'm not really convinced of the superiority of either, which has prevented me from taking definite action. Any thoughts between those two?

**Comment by plexus** [comment]
> I've been on the fence between wrapping it and just changing the API so that not finding an element returns nil. There are tradeoffs and I'm not really convinced of the superiority of either, which has prevented me from taking definite action. Any thoughts between those two?

There's something to be said for either. JavaScript seems to be on the side of returning `nil`.

``` javascript
document.getElementById("foo")
```

In the context of tests I think a descriptive exception is the preferred behavior. I'd rather have my tests fail with `"Element with CSS selector foo not found"` than with `NullPointerException`, but SparkleDriver isn't just for testing, and maybe there's something to be said for a separate library on top of SparkleDriver specifically geared towards testing that can take these things into account.

So... no real preference either way, I'll have my own wrapper for testing anyway. This is what the current incarnation looks like. Besides handling the exception it also retries a few times to find the element before giving up. Capybara does the same and I find it quite helpful to make tests less flaky.

``` clojure
(defn find-with-timeout [{:keys [finder browser selector timeout-millis] :or {timeout-millis 5000}}]
  (let [start-time (System/currentTimeMillis)
        timeout?   #(> (- (System/currentTimeMillis) start-time) timeout-millis)]
    (loop []
      (let [element (try
                      (finder browser selector)
                      (catch NoSuchElementException e
                        (if (timeout?)
                          (let [expected (list (-> finder meta :name) selector)
                                actual   (list 'not expected)
                                message  (str "No such element: " selector)]
                            (test/report {:type :error :message message :expected expected :actual actual})
                            :timeout)
                          :not-found)))]
        (if (= element :not-found)
          (recur)
          element)))))

(defn find-by-css [selector]
  (find-with-timeout {:finder #'sd/find-by-css :browser (browser) :selector selector}))

(defn find-by-css* [selector]
  (find-with-timeout {:finder #'sd/find-by-css* :browser (browser) :selector selector}))

(defn find-by-xpath [selector]
  (find-with-timeout {:finder #'sd/find-by-xpath :browser (browser) :selector selector}))

(defn find-by-xpath* [selector]
  (find-with-timeout {:finder #'sd/find-by-xpath :browser (browser) :selector selector}))
```

**Comment by jackrusher** [comment]
My primary production system that uses this library is a spider for a quite bad website (slow, sometimes fails to respond at all, sometimes gives transient bad results, &c). In that context I've also ended up with a timeout/retry wrapper that gets used for almost all operations.

The Selenium answer to this is the `Wait` API:
```
 Wait wait = new FluentWait(driver)
    .withTimeout(30, SECONDS)
    .pollingEvery(5, SECONDS)
    .ignoring(NoSuchElementException.class);
 
WebElement foo = wait.until(new Function() { 
    public WebElement apply(WebDriver driver) {
      return driver.findElement(By.id("foo"));
    }});
```

Would it be helpful to you if I added a more clojure-y API for this type of thing to `sparkledriver`?

**Comment by plexus** [comment]
In general that seems like a useful thing to have, yes.
